# FORMULA 1 DATA

A lo largo de este trabajo vamos a hacer uso de la API documentation de formula 1 en formato json donde se que provee datos desde 1950 para obtener distintas tablas con información de nuestro interés.
Para poder hacerlo importaremos las siguientes librerias con las que trabajaremos.

In [1]:
import requests
import json
import pandas as pd 

import warnings #Para que no nos salgan los warnings
warnings.filterwarnings("ignore")

Por practicidad solo trabajaremos exportando datos de la F1 de 2010 hasta 2022.

# Tabla de races

Vamos a explorar los datos de 2010 para ver con lo que trabajaremos

In [3]:
url="https://ergast.com/api/f1/2010.json"
response=requests.get(url)
content=json.loads(response.content)

In [5]:
content["MRData"]["RaceTable"]["Races"][0]

{'season': '2010',
 'round': '1',
 'url': 'http://en.wikipedia.org/wiki/2010_Bahrain_Grand_Prix',
 'raceName': 'Bahrain Grand Prix',
 'Circuit': {'circuitId': 'bahrain',
  'url': 'http://en.wikipedia.org/wiki/Bahrain_International_Circuit',
  'circuitName': 'Bahrain International Circuit',
  'Location': {'lat': '26.0325',
   'long': '50.5106',
   'locality': 'Sakhir',
   'country': 'Bahrain'}},
 'date': '2010-03-14',
 'time': '12:00:00Z'}

Comenzamos a obteenr los datos de cada carrera, cada ronda, desde 2010 a 2022

In [81]:
races={"season":[],"round":[],"raceName":[],"circuitId":[],"lat":[],"long":[],"country":[],"date":[],"url":[]}
for year in list(range(2010,2023)):
    url="https://ergast.com/api/f1/{}.json?limit=3000"
    response=requests.get(url.format(year))
    content=json.loads(response.content)
    for item in content["MRData"]["RaceTable"]["Races"]:
        races["season"].append(int(item["season"]))
        races["round"].append(int(item["round"]))
        races["raceName"].append(item["raceName"])
        races["circuitId"].append((item["Circuit"])["circuitId"])
        races["lat"].append(float(item["Circuit"]["Location"]["lat"]))
        races["long"].append(float((item["Circuit"])["Location"]["long"]))
        races["country"].append(item["Circuit"]["Location"]["country"])
        races["date"].append(item["date"])
        races["url"].append(item["url"])

In [82]:
races=pd.DataFrame(races)
races

,season,round,raceName,circuitId,lat,long,country,date,url
0,2010,1,Bahrain Grand Prix,bahrain,26.03250,50.51060,Bahrain,2010-03-14,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...
1,2010,2,Australian Grand Prix,albert_park,-37.84970,144.96800,Australia,2010-03-28,http://en.wikipedia.org/wiki/2010_Australian_G...
2,2010,3,Malaysian Grand Prix,sepang,2.76083,101.73800,Malaysia,2010-04-04,http://en.wikipedia.org/wiki/2010_Malaysian_Gr...
3,2010,4,Chinese Grand Prix,shanghai,31.33890,121.22000,China,2010-04-18,http://en.wikipedia.org/wiki/2010_Chinese_Gran...
4,2010,5,Spanish Grand Prix,catalunya,41.57000,2.26111,Spain,2010-05-09,http://en.wikipedia.org/wiki/2010_Spanish_Gran...
...,...,...,...,...,...,...,...,...,...
254,2022,18,Japanese Grand Prix,suzuka,34.84310,136.54100,Japan,2022-10-09,http://en.wikipedia.org/wiki/2022_Japanese_Gra...
255,2022,19,United States Grand Prix,americas,30.13280,-97.64110,USA,2022-10-23,http://en.wikipedia.org/wiki/2022_United_State...
256,2022,20,Mexico City Grand Prix,rodriguez,19.40420,-99.09070,Mexico,2022-10-30,http://en.wikipedia.org/wiki/2022_Mexican_Gran...
257,2022,21,Brazilian Grand Prix,interlagos,-23.70360,-46.69970,Brazil,2022-11-13,http://en.wikipedia.org/wiki/2022_Brazilian_Gr...
258,2022,22,Abu Dhabi Grand Prix,yas_marina,24.46720,54.60310,UAE,2022-11-20,http://en.wikipedia.org/wiki/2022_Abu_Dhabi_Gr...

In [71]:
races.to_csv("races.csv", index=False)

## Tabla de seasons

Vamos a explorar los datos de season 2010 para observar con que trabajaremos

In [6]:
url="https://ergast.com/api/f1/2010/seasons.json"
response=requests.get(url)
content=json.loads(response.content)

In [7]:
content["MRData"]["SeasonTable"]["Seasons"]

[{'season': '2010',
  'url': 'http://en.wikipedia.org/wiki/2010_Formula_One_season'}]

Ahora obtenemos los datos del año y url de cada season desde 2010 hasta 2022

In [92]:
seasons ={'season':[],'url':[]}
for year in list(range(2010,2023)):
    url="https://ergast.com/api/f1/{}/seasons.json?limit=3000"
    response=requests.get(url.format(year))
    content=json.loads(response.content)
    for item in content['MRData']['SeasonTable']['Seasons']:
        seasons['season'].append(int(item['season']))
        seasons['url'].append(item['url'])

In [93]:
seasons=pd.DataFrame(seasons)
seasons

    season                                                url
0     2010  http://en.wikipedia.org/wiki/2010_Formula_One_...
1     2011  http://en.wikipedia.org/wiki/2011_Formula_One_...
2     2012  http://en.wikipedia.org/wiki/2012_Formula_One_...
3     2013  http://en.wikipedia.org/wiki/2013_Formula_One_...
4     2014  http://en.wikipedia.org/wiki/2014_Formula_One_...
5     2015  http://en.wikipedia.org/wiki/2015_Formula_One_...
6     2016  http://en.wikipedia.org/wiki/2016_Formula_One_...
7     2017  http://en.wikipedia.org/wiki/2017_Formula_One_...
8     2018  http://en.wikipedia.org/wiki/2018_Formula_One_...
9     2019  http://en.wikipedia.org/wiki/2019_Formula_One_...
10    2020  http://en.wikipedia.org/wiki/2020_Formula_One_...
11    2021  http://en.wikipedia.org/wiki/2021_Formula_One_...
12    2022  http://en.wikipedia.org/wiki/2022_Formula_One_...

In [96]:
seasons.to_csv("seasons.csv",index=False)

## Tabla de drivers

Observamos los tipos de datos que nos muestra drivers para crear el DataFrame

In [8]:
url="http://ergast.com/api/f1/2010/drivers.json"
response=requests.get(url)
content=json.loads(response.content)

In [9]:
content["MRData"]["DriverTable"]["Drivers"][0]

{'driverId': 'alguersuari',
 'code': 'ALG',
 'url': 'http://en.wikipedia.org/wiki/Jaime_Alguersuari',
 'givenName': 'Jaime',
 'familyName': 'Alguersuari',
 'dateOfBirth': '1990-03-23',
 'nationality': 'Spanish'}

In [15]:
i=0
drivers={"driverId":[],"year":[],"driverRef":[],"number":[],"forename":[],"surname":[],"dob":[],"nationality":[],"url":[]}
for year in list(range(2010,2023)):
    url="https://ergast.com/api/f1/{}/drivers.json"
    response=requests.get(url.format(year))
    content=json.loads(response.content)
    for item in content['MRData']['DriverTable']['Drivers']:
        i=i+1
        drivers['driverId'].append(i)
        drivers["year"].append(year)
        try:
            drivers['driverRef'].append(item["driverId"])
        except:
            drivers['driverRef'].append(None)
        try:
            drivers["number"].append(item["permanentNumber"])
        except:
             drivers["number"].append(None)
        try:
            drivers['forename'].append(item["givenName"])
        except:
            drivers['forename'].append(None)
        try:
            drivers['surname'].append(item["familyName"])
        except:
            drivers['surname'].append(None)
        try:
            drivers['dob'].append(item["dateOfBirth"])
        except:
            drivers['dob'].append(None)
        try:
            drivers['nationality'].append(item["nationality"])
        except:
            drivers['nationality'].append(None)
        try:
            drivers["url"].append(item["url"])
        except:
            drivers["url"].append(None)

In [16]:
drivers=pd.DataFrame(drivers)
drivers

,driverId,year,driverRef,number,forename,surname,dob,nationality,url
0,1,2010,alguersuari,None,Jaime,Alguersuari,1990-03-23,Spanish,http://en.wikipedia.org/wiki/Jaime_Alguersuari
1,2,2010,alonso,14,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
2,3,2010,barrichello,None,Rubens,Barrichello,1972-05-23,Brazilian,http://en.wikipedia.org/wiki/Rubens_Barrichello
3,4,2010,buemi,None,Sébastien,Buemi,1988-10-31,Swiss,http://en.wikipedia.org/wiki/S%C3%A9bastien_Buemi
4,5,2010,button,22,Jenson,Button,1980-01-19,British,http://en.wikipedia.org/wiki/Jenson_Button
...,...,...,...,...,...,...,...,...,...
299,300,2022,stroll,18,Lance,Stroll,1998-10-29,Canadian,http://en.wikipedia.org/wiki/Lance_Stroll
300,301,2022,tsunoda,22,Yuki,Tsunoda,2000-05-11,Japanese,http://en.wikipedia.org/wiki/Yuki_Tsunoda
301,302,2022,max_verstappen,33,Max,Verstappen,1997-09-30,Dutch,http://en.wikipedia.org/wiki/Max_Verstappen
302,303,2022,vettel,5,Sebastian,Vettel,1987-07-03,German,http://en.wikipedia.org/wiki/Sebastian_Vettel
303,304,2022,zhou,24,Guanyu,Zhou,1999-05-30,Chinese,http://en.wikipedia.org/wiki/Guanyu_Zhou

In [17]:
drivers.to_csv("drivers.csv", index=False)

## Tabla de constructors

Observemos la API de constrcutores del 2010 para ver las variables con las que trabajaremos

In [11]:
url="https://ergast.com/api/f1/2010/constructors.json"
response=requests.get(url)
content=json.loads(response.content)

In [12]:
content["MRData"]["ConstructorTable"]["Constructors"][0]

{'constructorId': 'ferrari',
 'url': 'http://en.wikipedia.org/wiki/Scuderia_Ferrari',
 'name': 'Ferrari',
 'nationality': 'Italian'}

Creamos el codigo general para el Dataframe de 2010 a 2022

In [24]:
i=0
constructors={"constructorId":[],"year":[],"constructorRef":[],"name":[],"nationality":[],"url":[]}
for year in list(range(2010,2023)):
    url="https://ergast.com/api/f1/{}/constructors.json"
    response=requests.get(url.format(year))
    content=json.loads(response.content)
    for item in content['MRData']['ConstructorTable']['Constructors']:
        i=i+1
        constructors['constructorId'].append(i)
        constructors["year"].append(year)
        try:
            constructors['constructorRef'].append(item["constructorId"])
        except:
            constructors['constructorRef'].append(None)
        try:
            constructors["name"].append(item["name"])
        except:
            constructors["name"].append(None)
        try:
            constructors['nationality'].append(item["nationality"])
        except:
            constructors['nationality'].append(None)
        try:
            constructors["url"].append(item["url"])
        except:
            constructors["url"].append(None)

In [25]:
constructors=pd.DataFrame(constructors)
constructors

,constructorId,year,constructorRef,name,nationality,url
0,1,2010,ferrari,Ferrari,Italian,http://en.wikipedia.org/wiki/Scuderia_Ferrari
1,2,2010,force_india,Force India,Indian,http://en.wikipedia.org/wiki/Racing_Point_Forc...
2,3,2010,hrt,HRT,Spanish,http://en.wikipedia.org/wiki/Hispania_Racing
3,4,2010,lotus_racing,Lotus,Malaysian,http://en.wikipedia.org/wiki/Lotus_Racing
4,5,2010,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
...,...,...,...,...,...,...
134,135,2022,haas,Haas F1 Team,American,http://en.wikipedia.org/wiki/Haas_F1_Team
135,136,2022,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
136,137,2022,mercedes,Mercedes,German,http://en.wikipedia.org/wiki/Mercedes-Benz_in_...
137,138,2022,red_bull,Red Bull,Austrian,http://en.wikipedia.org/wiki/Red_Bull_Racing
138,139,2022,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...

In [27]:
constructors.to_csv("constructors.csv", index=False)

## Tabla de circuits

Observamos los circuits de 2010 para ver con que trabajaremos

In [18]:
url="http://ergast.com/api/f1/2010/circuits.json"
response=requests.get(url)
content=json.loads(response.content)

In [19]:
content['MRData']['CircuitTable']['Circuits'][0]

{'circuitId': 'albert_park',
 'url': 'http://en.wikipedia.org/wiki/Melbourne_Grand_Prix_Circuit',
 'circuitName': 'Albert Park Grand Prix Circuit',
 'Location': {'lat': '-37.8497',
  'long': '144.968',
  'locality': 'Melbourne',
  'country': 'Australia'}}

Ahora elaboramos el codigo para obtener el Dataframe de circuitos del 2010 a 2022

In [28]:
i=0
circuits={"circuitId":[],"year":[],"circuitRef":[],"name":[],"location":[],"country":[],"lat":[],"long":[],"url":[]}
for year in list(range(2010,2023)):
    url="https://ergast.com/api/f1/{}/circuits.json"
    response=requests.get(url.format(year))
    content=json.loads(response.content)
    for item in content['MRData']['CircuitTable']['Circuits']:
        i=i+1
        circuits['circuitId'].append(i)
        circuits["year"].append(year)
        try:
            circuits['circuitRef'].append(item["circuitId"])
        except:
            circuits['circuitRef'].append(None)
        try:
            circuits["name"].append(item["circuitName"])
        except:
            circuits["name"].append(None)
        try:
            circuits['location'].append(item["Location"]["locality"])
        except:
            circuits['location'].append(None)
        try:
            circuits["country"].append(item["Location"]["country"])
        except:
            circuits["country"].append(None)
        try:
            circuits["lat"].append(float(item["Location"]["lat"]))
        except:
            circuits["lat"].append(None)
        try:
            circuits["lng"].append(float(item["Location"]["long"]))
        except:
            circuits["long"].append(None)
        try:
            circuits["url"].append(item["url"])
        except:
            circuits["url"].append(None)

In [29]:
circuits=pd.DataFrame(circuits)
circuits

,circuitId,year,circuitRef,name,location,country,lat,long,url
0,1,2010,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,None,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2,2010,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.0325,None,http://en.wikipedia.org/wiki/Bahrain_Internati...
2,3,2010,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.5700,None,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
3,4,2010,hockenheimring,Hockenheimring,Hockenheim,Germany,49.3278,None,http://en.wikipedia.org/wiki/Hockenheimring
4,5,2010,hungaroring,Hungaroring,Budapest,Hungary,47.5789,None,http://en.wikipedia.org/wiki/Hungaroring
...,...,...,...,...,...,...,...,...,...
250,251,2022,spa,Circuit de Spa-Francorchamps,Spa,Belgium,50.4372,None,http://en.wikipedia.org/wiki/Circuit_de_Spa-Fr...
251,252,2022,suzuka,Suzuka Circuit,Suzuka,Japan,34.8431,None,http://en.wikipedia.org/wiki/Suzuka_Circuit
252,253,2022,villeneuve,Circuit Gilles Villeneuve,Montreal,Canada,45.5000,None,http://en.wikipedia.org/wiki/Circuit_Gilles_Vi...
253,254,2022,yas_marina,Yas Marina Circuit,Abu Dhabi,UAE,24.4672,None,http://en.wikipedia.org/wiki/Yas_Marina_Circuit
254,255,2022,zandvoort,Circuit Park Zandvoort,Zandvoort,Netherlands,52.3888,None,http://en.wikipedia.org/wiki/Circuit_Zandvoort

In [30]:
circuits.to_csv("circuits.csv", index=False)

## Tabla de qualifying

Exploremos un poco los datos que nos muestra qualifying en 2010 para ver con lo que trabajaremos

In [20]:
url="https://ergast.com/api/f1/2010/qualifying.json?limit=1000"
response=requests.get(url)
content=json.loads(response.content)

In [21]:
content["MRData"]["RaceTable"]["Races"][0]["QualifyingResults"][0]

{'number': '5',
 'position': '1',
 'Driver': {'driverId': 'vettel',
  'permanentNumber': '5',
  'code': 'VET',
  'url': 'http://en.wikipedia.org/wiki/Sebastian_Vettel',
  'givenName': 'Sebastian',
  'familyName': 'Vettel',
  'dateOfBirth': '1987-07-03',
  'nationality': 'German'},
 'Constructor': {'constructorId': 'red_bull',
  'url': 'http://en.wikipedia.org/wiki/Red_Bull_Racing',
  'name': 'Red Bull',
  'nationality': 'Austrian'},
 'Q1': '1:55.029',
 'Q2': '1:53.883',
 'Q3': '1:54.101'}

Ahora creamos el codigo para realizar el Dataframe de todas las clasificatorias desde 2010 a 2022

In [32]:
j=0
qualifying={"qualifyId":[],"year":[],"raceId":[],"driverId":[],"constructorId":[],"number":[],"position":[],"q1":[],"q2":[],"q3":[]}
for year in list(range(2010,2023)):
    url="https://ergast.com/api/f1/{}/qualifying.json?limit=1000"
    response=requests.get(url.format(year))
    content=json.loads(response.content)
    i=0
    for item in content['MRData']['RaceTable']['Races']:
        raceName=item["raceName"]
        for item in content['MRData']['RaceTable']['Races'][i]["QualifyingResults"]:
            j=j+1
            qualifying["qualifyId"].append(j)
            qualifying["year"].append(year)
            qualifying["raceId"].append(raceName)
            qualifying["number"].append(item["number"])
            qualifying["driverId"].append(item["Driver"]["driverId"])
            qualifying["constructorId"].append(item["Constructor"]["constructorId"])
            qualifying["position"].append(item["position"])
            qualifying["q1"].append(item["Q1"])
            try:
                qualifying["q2"].append(item["Q2"])
            except:
                qualifying["q2"].append(None)
            try:
                qualifying["q3"].append(item["Q3"])
            except:
                qualifying["q3"].append(None)
        i=i+1

In [33]:
qualifying=pd.DataFrame(qualifying)
qualifying

,qualifyId,year,raceId,driverId,constructorId,number,position,q1,q2,q3
0,1,2010,Bahrain Grand Prix,vettel,red_bull,5,1,1:55.029,1:53.883,1:54.101
1,2,2010,Bahrain Grand Prix,massa,ferrari,7,2,1:55.313,1:54.331,1:54.242
2,3,2010,Bahrain Grand Prix,alonso,ferrari,8,3,1:54.612,1:54.172,1:54.608
3,4,2010,Bahrain Grand Prix,hamilton,mclaren,2,4,1:55.341,1:54.707,1:55.217
4,5,2010,Bahrain Grand Prix,rosberg,mercedes,4,5,1:55.463,1:54.682,1:55.241
...,...,...,...,...,...,...,...,...,...,...
5488,5489,2022,Abu Dhabi Grand Prix,kevin_magnussen,haas,20,16,1:25.834,None,None
5489,5490,2022,Abu Dhabi Grand Prix,gasly,alphatauri,10,17,1:25.859,None,None
5490,5491,2022,Abu Dhabi Grand Prix,bottas,alfa,77,18,1:25.892,None,None
5491,5492,2022,Abu Dhabi Grand Prix,albon,williams,23,19,1:26.028,None,None
5492,5493,2022,Abu Dhabi Grand Prix,latifi,williams,6,20,1:26.054,None,None

In [34]:
qualifying.to_csv("qualifying.csv", index=False)

## Tabla de sprint Results

Al explorar los datos podemos observar que el API de sprint solo nos proporciona información de los años 2021 y 2022 por lo que serán con los que trabajaremos.

In [22]:
url="https://ergast.com/api/f1/2021/sprint.json"
response=requests.get(url)
content=json.loads(response.content)

In [25]:
content["MRData"]["RaceTable"]["Races"][0]["SprintResults"][0]

{'number': '33',
 'position': '1',
 'positionText': '1',
 'points': '3',
 'Driver': {'driverId': 'max_verstappen',
  'permanentNumber': '33',
  'code': 'VER',
  'url': 'http://en.wikipedia.org/wiki/Max_Verstappen',
  'givenName': 'Max',
  'familyName': 'Verstappen',
  'dateOfBirth': '1997-09-30',
  'nationality': 'Dutch'},
 'Constructor': {'constructorId': 'red_bull',
  'url': 'http://en.wikipedia.org/wiki/Red_Bull_Racing',
  'name': 'Red Bull',
  'nationality': 'Austrian'},
 'grid': '2',
 'laps': '17',
 'status': 'Finished',
 'Time': {'millis': '1538426', 'time': '25:38.426'},
 'FastestLap': {'lap': '14', 'Time': {'time': '1:30.013'}}}

Sabiendo esta información iniciamos con la extracción de los datos en 2021 y 2022 para posterioirmente crear un dataframe.

In [9]:
i=0
j=0
sprint={"sprintresultId":[],"year":[],"raceId":[],"driverId":[],"constructorId":[],"number":[],"grid":[],"position":[],"positionText":[],
       "points":[],"laps":[],"time":[],"milliseconds":[],"fastestLap":[],"fastestLapTime":[],"statusId":[]}#,"positionOrder":[]}
for year in list(range(2021,2023)):
    url="https://ergast.com/api/f1/{}/sprint.json?limit=1000"
    response=requests.get(url.format(year))
    content=json.loads(response.content)
    i=0
    for item in content['MRData']['RaceTable']['Races']:
        raceName=item["raceName"]
        for item in content['MRData']['RaceTable']['Races'][i]["SprintResults"]:
            j=j+1
            sprint["sprintresultId"].append(j)
            sprint["year"].append(year)
            sprint["raceId"].append(raceName)
            sprint["number"].append(int(item["number"]))
            sprint["driverId"].append(item["Driver"]["driverId"])
            sprint["constructorId"].append(item["Constructor"]["constructorId"])
            sprint["grid"].append(int(item["grid"]))
            sprint["position"].append(int(item["position"]))
            sprint["positionText"].append(item["positionText"])
            sprint["points"].append(int(item["points"]))
            sprint["laps"].append(int(item["laps"]))
            try:
                sprint["time"].append(item["Time"]["time"])
            except:
                sprint["time"].append(None)
            try:
                sprint["milliseconds"].append(item["Time"]["millis"])
            except:
                sprint["milliseconds"].append(None)
            try:
                sprint["fastestLap"].append(item["FastestLap"]["lap"])
            except:
                sprint["fastestLap"].append(None)
            try:
                sprint["fastestLapTime"].append(item["FastestLap"]["Time"]["time"])
            except:
                sprint["fastestLapTime"].append(None)
            sprint["statusId"].append(item["status"])
        i=i+1

In [10]:
sprint=pd.DataFrame(sprint)
sprint

,sprintresultId,year,raceId,driverId,constructorId,number,grid,position,positionText,points,laps,time,milliseconds,fastestLap,fastestLapTime,statusId
0,1,2021,British Grand Prix,max_verstappen,red_bull,33,2,1,1,3,17,25:38.426,1538426,14,1:30.013,Finished
1,2,2021,British Grand Prix,hamilton,mercedes,44,1,2,2,2,17,+1.430,1539856,17,1:29.937,Finished
2,3,2021,British Grand Prix,bottas,mercedes,77,3,3,3,1,17,+7.502,1545928,17,1:29.958,Finished
3,4,2021,British Grand Prix,leclerc,ferrari,16,4,4,4,0,17,+11.278,1549704,16,1:30.163,Finished
4,5,2021,British Grand Prix,norris,mclaren,4,6,5,5,0,17,+24.111,1562537,16,1:30.566,Finished
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,116,2022,Brazilian Grand Prix,stroll,aston_martin,18,15,16,16,0,24,+50.700,1862007,4,1:15.425,Finished
116,117,2022,Brazilian Grand Prix,ocon,alpine,31,6,17,17,0,24,+51.756,1863063,5,1:16.097,Finished
117,118,2022,Brazilian Grand Prix,alonso,alpine,14,7,18,18,0,24,+53.985,1865292,5,1:14.764,Finished
118,119,2022,Brazilian Grand Prix,latifi,williams,6,16,19,19,0,24,+1:16.850,1888157,4,1:16.525,Finished
119,120,2022,Brazilian Grand Prix,albon,williams,23,11,20,R,0,12,None,None,4,1:15.998,Retired

In [35]:
sprint.to_csv("sprintResults.csv", index=False)

## Tabla de status

Exploramos la base de datos cargando los status de 2010 para ver con lo que vamos a trabajar

In [ ]:
url="https://ergast.com/api/f1/2010/status.json?limit=1000"
response=requests.get(url)
content=json.loads(response.content)

In [11]:
content["MRData"]["StatusTable"]["Status"]

[{'statusId': '1', 'count': '212', 'status': 'Finished'},
 {'statusId': '3', 'count': '17', 'status': 'Accident'},
 {'statusId': '4', 'count': '25', 'status': 'Collision'},
 {'statusId': '5', 'count': '13', 'status': 'Engine'},
 {'statusId': '6', 'count': '9', 'status': 'Gearbox'},
 {'statusId': '8', 'count': '1', 'status': 'Clutch'},
 {'statusId': '9', 'count': '19', 'status': 'Hydraulics'},
 {'statusId': '10', 'count': '1', 'status': 'Electrical'},
 {'statusId': '11', 'count': '68', 'status': '+1 Lap'},
 {'statusId': '12', 'count': '31', 'status': '+2 Laps'},
 {'statusId': '13', 'count': '13', 'status': '+3 Laps'},
 {'statusId': '14', 'count': '8', 'status': '+4 Laps'},
 {'statusId': '15', 'count': '3', 'status': '+5 Laps'},
 {'statusId': '16', 'count': '1', 'status': '+6 Laps'},
 {'statusId': '19', 'count': '1', 'status': '+9 Laps'},
 {'statusId': '20', 'count': '2', 'status': 'Spun off'},
 {'statusId': '22', 'count': '6', 'status': 'Suspension'},
 {'statusId': '23', 'count': '3', 'status': 'Brakes'},
 {'statusId': '25', 'count': '1', 'status': 'Overheating'},
 {'statusId': '26', 'count': '1', 'status': 'Mechanical'},
 {'statusId': '29', 'count': '1', 'status': 'Puncture'},
 {'statusId': '30', 'count': '1', 'status': 'Driveshaft'},
 {'statusId': '31', 'count': '3', 'status': 'Retired'},
 {'statusId': '32', 'count': '1', 'status': 'Fuel pressure'},
 {'statusId': '33', 'count': '1', 'status': 'Front wing'},
 {'statusId': '36', 'count': '5', 'status': 'Wheel'},
 {'statusId': '37', 'count': '1', 'status': 'Throttle'},
 {'statusId': '38', 'count': '1', 'status': 'Steering'},
 {'statusId': '39', 'count': '1', 'status': 'Technical'},
 {'statusId': '43', 'count': '1', 'status': 'Exhaust'},
 {'statusId': '44', 'count': '1', 'status': 'Oil leak'},
 {'statusId': '48', 'count': '1', 'status': 'Fuel pump'},
 {'statusId': '49', 'count': '1', 'status': 'Track rod'},
 {'statusId': '65', 'count': '1', 'status': 'Rear wing'},
 {'statusId': '88', 'count': '1', 'status': '+10 Laps'}]

Elaboramos el codigo para obtener un dataframe de status desde 2010 hasta 2022

In [12]:
status={"year":[],"statusId":[],"status":[]}
for year in list(range(2010,2023)):
    url="https://ergast.com/api/f1/{}/status.json?limit=1000"
    response=requests.get(url.format(year))
    content=json.loads(response.content)
    for item in content['MRData']['StatusTable']['Status']:
        status['statusId'].append(item["statusId"])
        status["year"].append(year)
        status["status"].append(item["status"])

In [13]:
status=pd.DataFrame(status)
status

     year statusId            status
0    2010        1          Finished
1    2010        3          Accident
2    2010        4         Collision
3    2010        5            Engine
4    2010        6           Gearbox
..    ...      ...               ...
364  2022      103        Water pump
365  2022      130  Collision damage
366  2022      131        Power Unit
367  2022      140         Undertray
368  2022      141    Cooling system

[369 rows x 3 columns]

In [36]:
status.to_csv("status.csv", index=False)

## Tabla de results

Primero exploramos los results del 2010 como ejemplo para ver el tipo de datos con los que vamos a trabajar.

In [26]:
url="https://ergast.com/api/f1/2010/results.json?limit=1000"
response=requests.get(url)
content=json.loads(response.content)

In [29]:
content["MRData"]["RaceTable"]["Races"][0]["Results"][0]

{'number': '8',
 'position': '1',
 'positionText': '1',
 'points': '25',
 'Driver': {'driverId': 'alonso',
  'permanentNumber': '14',
  'code': 'ALO',
  'url': 'http://en.wikipedia.org/wiki/Fernando_Alonso',
  'givenName': 'Fernando',
  'familyName': 'Alonso',
  'dateOfBirth': '1981-07-29',
  'nationality': 'Spanish'},
 'Constructor': {'constructorId': 'ferrari',
  'url': 'http://en.wikipedia.org/wiki/Scuderia_Ferrari',
  'name': 'Ferrari',
  'nationality': 'Italian'},
 'grid': '3',
 'laps': '49',
 'status': 'Finished',
 'Time': {'millis': '5960396', 'time': '1:39:20.396'},
 'FastestLap': {'rank': '1',
  'lap': '45',
  'Time': {'time': '1:58.287'},
  'AverageSpeed': {'units': 'kph', 'speed': '191.706'}}}

Ahora elaboramos el codigo para extraer los results desde 2010 hasta 2023

In [15]:
j=0
results={"resultId":[],"year":[],"raceId":[],"driverId":[],"constructorId":[],"number":[],"grid":[],"position":[],"positionText":[],"points":[],"laps":[],
        "time":[],"milliseconds":[],"fastestLap":[],"rank":[],"fastestLapTime":[],"fastestLapSpeed":[],"status":[]}
for year in list(range(2010,2023)):
    url="https://ergast.com/api/f1/{}/results.json?limit=1000"
    response=requests.get(url.format(year))
    content=json.loads(response.content)
    i=0
    for item in content['MRData']['RaceTable']['Races']:
        raceName=item["raceName"]
        for item in content['MRData']['RaceTable']['Races'][i]["Results"]:
            j=j+1
            results["resultId"].append(j)
            results["year"].append(year)
            results["raceId"].append(raceName)
            results["number"].append(item["number"])
            results["driverId"].append(item["Driver"]["driverId"])
            results["constructorId"].append(item["Constructor"]["constructorId"])
            results["position"].append(item["position"])
            results["grid"].append(int(item["grid"]))
            results["positionText"].append(item["positionText"])
            results["points"].append(item["points"])
            results["laps"].append(int(item["laps"]))
            try:
                results["time"].append(item["Time"]["time"])
            except:
                results["time"].append(None)
            try:
                results["milliseconds"].append(item["Time"]["millis"])
            except:
                results["milliseconds"].append(None)
            try:
                results["fastestLap"].append(item["FastestLap"]["lap"])
            except:
                results["fastestLap"].append(None)
            try:
                results["fastestLapTime"].append(item["FastestLap"]["Time"]["time"])
            except:
                results["fastestLapTime"].append(None)
            try:
                results["rank"].append(item["FastestLap"]["rank"])
            except:
                results["rank"].append(None)
            try:
                results["fastestLapSpeed"].append(item["FastestLap"]["AverageSpeed"]["speed"])
            except:
                results["fastestLapSpeed"].append(None)
            results["status"].append(item["status"])
        i=i+1

In [37]:
results=pd.DataFrame(results)
results

,resultId,year,raceId,driverId,constructorId,number,grid,position,positionText,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,status
0,1,2010,Bahrain Grand Prix,alonso,ferrari,8,3,1,1,25,49,1:39:20.396,5960396,45,1,1:58.287,191.706,Finished
1,2,2010,Bahrain Grand Prix,massa,ferrari,7,2,2,2,18,49,+16.099,5976495,38,5,1:59.732,189.392,Finished
2,3,2010,Bahrain Grand Prix,hamilton,mclaren,2,4,3,3,15,49,+23.182,5983578,42,4,1:59.560,189.665,Finished
3,4,2010,Bahrain Grand Prix,vettel,red_bull,5,1,4,4,12,49,+38.799,5999195,32,12,2:00.218,188.627,Finished
4,5,2010,Bahrain Grand Prix,rosberg,mercedes,4,5,5,5,10,49,+40.213,6000609,45,13,2:00.236,188.599,Finished
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5512,5513,2022,Abu Dhabi Grand Prix,mick_schumacher,haas,47,12,16,16,0,57,None,None,39,12,1:29.833,211.632,+1 Lap
5513,5514,2022,Abu Dhabi Grand Prix,kevin_magnussen,haas,20,16,17,17,0,57,None,None,40,20,1:31.158,208.556,+1 Lap
5514,5515,2022,Abu Dhabi Grand Prix,hamilton,mercedes,44,5,18,18,0,55,None,None,42,11,1:29.788,211.738,Hydraulics
5515,5516,2022,Abu Dhabi Grand Prix,latifi,williams,6,20,19,19,0,55,None,None,45,14,1:30.309,210.517,Collision damage
5516,5517,2022,Abu Dhabi Grand Prix,alonso,alpine,14,10,20,R,0,27,None,None,24,17,1:30.579,209.889,Water leak

In [38]:
results.to_csv("results.csv", index=False)

## Tabla de pitstop

Vamos a explorar un poco los datos de pitstop en 2011 ronda 1 para observar con lo que vamos a trabajar. Vemos que los datos solo se presentan de 2011 en adelante.

In [30]:
url="http://ergast.com/api/f1/2011/1/pitstops.json?limit=1000"
response=requests.get(url)
content=json.loads(response.content)

In [32]:
content["MRData"]["RaceTable"]["Races"][0]["PitStops"][0]

{'driverId': 'alguersuari',
 'lap': '1',
 'stop': '1',
 'time': '17:05:23',
 'duration': '26.898'}

Ahora elaboramos el codigo para los datos de 2011 a 2022

In [19]:
pitstop={"year":[],"round":[],"raceId":[],"driverId":[],"stop":[],"lap":[],"time":[],"duration":[]}
for year in list(range(2010,2023)):
    url="https://ergast.com/api/f1/{}.json?limit=1000"
    response=requests.get(url.format(year))
    content=json.loads(response.content)
    w=len(content["MRData"]["RaceTable"]["Races"])
    for roundd in list(range(1,w+1)):
        url="https://ergast.com/api/f1/{}/{}/pitstops.json?limit=1000"
        response=requests.get(url.format(year,roundd))
        content=json.loads(response.content)
        for item in content['MRData']['RaceTable']['Races']:
            raceName=item["raceName"]
            for item in content['MRData']['RaceTable']['Races'][0]["PitStops"]:
                pitstop["year"].append(year)
                pitstop["round"].append(roundd)
                pitstop["raceId"].append(raceName)
                pitstop["stop"].append(item["stop"])
                pitstop["driverId"].append(item["driverId"])
                pitstop["lap"].append(item["lap"])
                pitstop["time"].append(item["time"])
                pitstop["duration"].append(item["duration"])

In [20]:
pitstop=pd.DataFrame(pitstop)
pitstop

,year,round,raceId,driverId,stop,lap,time,duration
0,2011,1,Australian Grand Prix,alguersuari,1,1,17:05:23,26.898
1,2011,1,Australian Grand Prix,michael_schumacher,1,1,17:05:52,25.021
2,2011,1,Australian Grand Prix,webber,1,11,17:20:48,23.426
3,2011,1,Australian Grand Prix,alonso,1,12,17:22:34,23.251
4,2011,1,Australian Grand Prix,massa,1,13,17:24:10,23.842
...,...,...,...,...,...,...,...,...
9629,2022,22,Abu Dhabi Grand Prix,latifi,2,38,18:02:50,25.174
9630,2022,22,Abu Dhabi Grand Prix,stroll,2,40,18:04:44,21.802
9631,2022,22,Abu Dhabi Grand Prix,ocon,2,41,18:06:09,21.734
9632,2022,22,Abu Dhabi Grand Prix,norris,2,42,18:07:36,21.559
9633,2022,22,Abu Dhabi Grand Prix,zhou,2,44,18:11:10,23.159

In [39]:
pitstop.to_csv("pitStops.csv", index=False)

## Tabla de lapTimes

Exploramos los datos que nos brinda el Api de laptimes para la ronda 1 del 2010

In [5]:
url="http://ergast.com/api/f1/2010/1/laps.json?limit=5000"
response=requests.get(url)
content=json.loads(response.content)

In [6]:
content["MRData"]["RaceTable"]["Races"][0]["Laps"][0]["Timings"]

[{'driverId': 'vettel', 'position': '1', 'time': '2:03.366'},
 {'driverId': 'alonso', 'position': '2', 'time': '2:05.394'},
 {'driverId': 'massa', 'position': '3', 'time': '2:06.758'},
 {'driverId': 'rosberg', 'position': '4', 'time': '2:08.063'},
 {'driverId': 'hamilton', 'position': '5', 'time': '2:08.558'},
 {'driverId': 'michael_schumacher', 'position': '6', 'time': '2:09.527'},
 {'driverId': 'webber', 'position': '7', 'time': '2:09.956'},
 {'driverId': 'button', 'position': '8', 'time': '2:10.721'},
 {'driverId': 'liuzzi', 'position': '9', 'time': '2:11.473'},
 {'driverId': 'barrichello', 'position': '10', 'time': '2:12.361'},
 {'driverId': 'petrov', 'position': '11', 'time': '2:12.963'},
 {'driverId': 'kobayashi', 'position': '12', 'time': '2:13.768'},
 {'driverId': 'hulkenberg', 'position': '13', 'time': '2:14.245'},
 {'driverId': 'rosa', 'position': '14', 'time': '2:14.907'},
 {'driverId': 'alguersuari', 'position': '15', 'time': '2:15.479'},
 {'driverId': 'kovalainen', 'position': '16', 'time': '2:17.386'},
 {'driverId': 'buemi', 'position': '17', 'time': '2:18.065'},
 {'driverId': 'glock', 'position': '18', 'time': '2:18.573'},
 {'driverId': 'grassi', 'position': '19', 'time': '2:19.114'},
 {'driverId': 'trulli', 'position': '20', 'time': '2:19.666'},
 {'driverId': 'kubica', 'position': '21', 'time': '2:20.006'},
 {'driverId': 'sutil', 'position': '22', 'time': '2:24.476'},
 {'driverId': 'bruno_senna', 'position': '23', 'time': '2:27.750'},
 {'driverId': 'chandhok', 'position': '24', 'time': '2:34.479'}]

Realizamos el codigo para obtener los datos deseados de los timepos de vuelta por cada corredor,cada ronda, del 2010 al 2022.

In [7]:
lapTime={"year":[],"round":[],"raceId":[],"driverId":[],"lap":[],"position":[],"time":[]}
for year in list(range(2010,2023)):
    url="https://ergast.com/api/f1/{}.json?limit=5000"
    response=requests.get(url.format(year))
    content=json.loads(response.content)
    w=len(content["MRData"]["RaceTable"]["Races"])
    for roundd in list(range(1,w+1)):
        url="https://ergast.com/api/f1/{}/{}/laps.json?limit=5000"
        response=requests.get(url.format(year,roundd))
        content=json.loads(response.content)
        z=len(content["MRData"]["RaceTable"]["Races"][0]["Laps"])
        for item in content['MRData']['RaceTable']['Races']:
            raceName=item["raceName"]
            for i in list(range(0,z)):
                lap=content["MRData"]["RaceTable"]["Races"][0]["Laps"][i]["number"]
                for item in content['MRData']['RaceTable']['Races'][0]["Laps"][i]["Timings"]:
                    lapTime["year"].append(year)
                    lapTime["round"].append(roundd)
                    lapTime["raceId"].append(raceName)
                    lapTime["driverId"].append(item["driverId"])
                    lapTime["lap"].append(lap)
                    lapTime["position"].append(item["position"])
                    lapTime["time"].append(item["time"])

In [8]:
lapTime=pd.DataFrame(lapTime)
lapTime

        year  round                raceId   driverId lap position      time
0       2010      1    Bahrain Grand Prix     vettel   1        1  2:03.366
1       2010      1    Bahrain Grand Prix     alonso   1        2  2:05.394
2       2010      1    Bahrain Grand Prix      massa   1        3  2:06.758
3       2010      1    Bahrain Grand Prix    rosberg   1        4  2:08.063
4       2010      1    Bahrain Grand Prix   hamilton   1        5  2:08.558
...      ...    ...                   ...        ...  ..      ...       ...
291843  2022     22  Abu Dhabi Grand Prix       ocon  58        7  1:30.021
291844  2022     22  Abu Dhabi Grand Prix     stroll  58        8  1:31.330
291845  2022     22  Abu Dhabi Grand Prix  ricciardo  58        9  1:30.856
291846  2022     22  Abu Dhabi Grand Prix     vettel  58       10  1:30.351
291847  2022     22  Abu Dhabi Grand Prix    tsunoda  58       11  1:32.280

[291848 rows x 7 columns]

In [9]:
lapTime.to_csv("lapTimes.csv", index=False)

## Tabla de Driverstandings

Exploramos los datos de los conductores de la ronda 1 del año 2010 para observar con lo que vamos. a trabajar:

In [33]:
url="http://ergast.com/api/f1/2010/1/driverStandings.json?limit=5000"
response=requests.get(url)
content=json.loads(response.content)

In [34]:
content["MRData"]["StandingsTable"]["StandingsLists"][0]["DriverStandings"][0]

{'position': '1',
 'positionText': '1',
 'points': '25',
 'wins': '1',
 'Driver': {'driverId': 'alonso',
  'permanentNumber': '14',
  'code': 'ALO',
  'url': 'http://en.wikipedia.org/wiki/Fernando_Alonso',
  'givenName': 'Fernando',
  'familyName': 'Alonso',
  'dateOfBirth': '1981-07-29',
  'nationality': 'Spanish'},
 'Constructors': [{'constructorId': 'ferrari',
   'url': 'http://en.wikipedia.org/wiki/Scuderia_Ferrari',
   'name': 'Ferrari',
   'nationality': 'Italian'}]}

Realizamos el codigo para los datos desde 2010 a 2022.

In [14]:
i=0
driverStandings={"driverStandingsId":[],"year":[],"round":[],"driverId":[],"points":[],"position":[],"positionText":[],"wins":[]}
for year in list(range(2010,2023)):
    url="https://ergast.com/api/f1/{}.json?limit=1000"
    response=requests.get(url.format(year))
    content=json.loads(response.content)
    w=len(content["MRData"]["RaceTable"]["Races"])
    for roundd in list(range(1,w+1)):
        url="https://ergast.com/api/f1/{}/{}/driverStandings.json?limit=5000"
        response=requests.get(url.format(year,roundd))
        content=json.loads(response.content)
        for item in content['MRData']["StandingsTable"]["StandingsLists"][0]["DriverStandings"]:
            i=i+1
            driverStandings["driverStandingsId"].append(i)
            driverStandings["year"].append(year)
            driverStandings["round"].append(roundd)
            driverStandings["driverId"].append(item["Driver"]["driverId"])
            driverStandings["position"].append(item["position"])
            driverStandings["positionText"].append(item["positionText"])
            driverStandings["points"].append(item["points"])
            driverStandings["wins"].append(item["wins"])

In [15]:
driverStandings=pd.DataFrame(driverStandings)
driverStandings

,driverStandingsId,year,round,driverId,points,position,positionText,wins
0,1,2010,1,alonso,25,1,1,1
1,2,2010,1,massa,18,2,2,0
2,3,2010,1,hamilton,15,3,3,0
3,4,2010,1,vettel,12,4,4,0
4,5,2010,1,rosberg,10,5,5,0
...,...,...,...,...,...,...,...,...
5762,5763,2022,22,zhou,6,18,18,0
5763,5764,2022,22,albon,4,19,19,0
5764,5765,2022,22,latifi,2,20,20,0
5765,5766,2022,22,de_vries,2,21,21,0
5766,5767,2022,22,hulkenberg,0,22,22,0

In [16]:
driverStandings.to_csv("driverStandings.csv",index=False)

## Tabla de constructorStandings

Exploremos los datos de constructor de la ronda 1 del año 2010 para observar con lo que vamos a trabajar

In [36]:
url="http://ergast.com/api/f1/2010/1/constructorStandings.json?limit=5000"
response=requests.get(url)
content=json.loads(response.content)

In [37]:
content["MRData"]["StandingsTable"]["StandingsLists"][0]["ConstructorStandings"][0]

{'position': '1',
 'positionText': '1',
 'points': '43',
 'wins': '1',
 'Constructor': {'constructorId': 'ferrari',
  'url': 'http://en.wikipedia.org/wiki/Scuderia_Ferrari',
  'name': 'Ferrari',
  'nationality': 'Italian'}}

Realizamos el codigo para obtener los reusltados de los constructores de cada ronda en cada año desde 2010 a 2022

In [24]:
i=0
constructorStandings={"constructorStandingsId":[],"year":[],"round":[],"constructorId":[],"points":[],"position":[],"positionText":[],"wins":[]}
for year in list(range(2010,2023)):
    url="https://ergast.com/api/f1/{}.json?limit=1000"
    response=requests.get(url.format(year))
    content=json.loads(response.content)
    w=len(content["MRData"]["RaceTable"]["Races"])
    for roundd in list(range(1,w+1)):
        url="https://ergast.com/api/f1/{}/{}/constructorStandings.json?limit=5000"
        response=requests.get(url.format(year,roundd))
        content=json.loads(response.content)
        for item in content['MRData']["StandingsTable"]["StandingsLists"][0]["ConstructorStandings"]:
            i=i+1
            constructorStandings["constructorStandingsId"].append(i)
            constructorStandings["round"].append(roundd)
            constructorStandings["year"].append(year)
            constructorStandings["constructorId"].append(item["Constructor"]["constructorId"])
            constructorStandings["position"].append(item["position"])
            constructorStandings["positionText"].append(item["positionText"])
            constructorStandings["points"].append(item["points"])
            constructorStandings["wins"].append(item["wins"])

In [25]:
constructorStandings=pd.DataFrame(constructorStandings)
constructorStandings

,constructorStandingsId,year,round,constructorId,points,position,positionText,wins
0,1,2010,1,ferrari,43,1,1,1
1,2,2010,1,mclaren,21,2,2,0
2,3,2010,1,mercedes,18,3,3,0
3,4,2010,1,red_bull,16,4,4,0
4,5,2010,1,force_india,2,5,5,0
...,...,...,...,...,...,...,...,...
2756,2757,2022,22,alfa,55,6,6,0
2757,2758,2022,22,aston_martin,55,7,7,0
2758,2759,2022,22,haas,37,8,8,0
2759,2760,2022,22,alphatauri,35,9,9,0
2760,2761,2022,22,williams,8,10,10,0

In [26]:
constructorStandings.to_csv("constructorStandings.csv",index=False)

## Tabla de constructorResults

Para realizar eesta tabla nos basaremos en el trabajo hecho en la tabla "results" de donde extraeremos los datos de interés como lo son constructor, raceId, points y status.
Para ello exploraremos los datos de results en la ronda1 del año 2010

In [38]:
url="https://ergast.com/api/f1/2010/1/results.json?limit=1000"
response=requests.get(url)
content=json.loads(response.content)

In [40]:
content["MRData"]["RaceTable"]["Races"][0]["Results"][0]

{'number': '8',
 'position': '1',
 'positionText': '1',
 'points': '25',
 'Driver': {'driverId': 'alonso',
  'permanentNumber': '14',
  'code': 'ALO',
  'url': 'http://en.wikipedia.org/wiki/Fernando_Alonso',
  'givenName': 'Fernando',
  'familyName': 'Alonso',
  'dateOfBirth': '1981-07-29',
  'nationality': 'Spanish'},
 'Constructor': {'constructorId': 'ferrari',
  'url': 'http://en.wikipedia.org/wiki/Scuderia_Ferrari',
  'name': 'Ferrari',
  'nationality': 'Italian'},
 'grid': '3',
 'laps': '49',
 'status': 'Finished',
 'Time': {'millis': '5960396', 'time': '1:39:20.396'},
 'FastestLap': {'rank': '1',
  'lap': '45',
  'Time': {'time': '1:58.287'},
  'AverageSpeed': {'units': 'kph', 'speed': '191.706'}}}

Ahora bien realizamos un codigo muy similar al de results para extraer estos datos de interés.

In [56]:
j=0
constructorResults2={"Id":[],"year":[],"round":[],"raceId":[],"constructorId":[],"points":[],"status":[]}
for year in list(range(2010,2023)):
    url="https://ergast.com/api/f1/{}/results.json?limit=1000"
    response=requests.get(url.format(year))
    content=json.loads(response.content)
    i=0
    for item in content['MRData']['RaceTable']['Races']:
        raceName=item["raceName"]
        for item in content['MRData']['RaceTable']['Races'][i]["Results"]:
            j=j+1
            season=content['MRData']['RaceTable']['Races'][i]["round"]
            constructorResults2["Id"].append(j)
            constructorResults2["round"].append(int(season))
            constructorResults2["year"].append(year)
            constructorResults2["raceId"].append(raceName)
            constructorResults2["constructorId"].append(item["Constructor"]["constructorId"])
            constructorResults2["points"].append(float(item["points"]))
            constructorResults2["status"].append(item["status"])
        i=i+1

In [57]:
constructorResults2=pd.DataFrame(constructorResults2)
constructorResults2["status"]=constructorResults2["status"]+"."
constructorResults2

,Id,year,round,raceId,constructorId,points,status
0,1,2010,1,Bahrain Grand Prix,ferrari,25.0,Finished.
1,2,2010,1,Bahrain Grand Prix,ferrari,18.0,Finished.
2,3,2010,1,Bahrain Grand Prix,mclaren,15.0,Finished.
3,4,2010,1,Bahrain Grand Prix,red_bull,12.0,Finished.
4,5,2010,1,Bahrain Grand Prix,mercedes,10.0,Finished.
...,...,...,...,...,...,...,...
5512,5513,2022,22,Abu Dhabi Grand Prix,haas,0.0,+1 Lap.
5513,5514,2022,22,Abu Dhabi Grand Prix,haas,0.0,+1 Lap.
5514,5515,2022,22,Abu Dhabi Grand Prix,mercedes,0.0,Hydraulics.
5515,5516,2022,22,Abu Dhabi Grand Prix,williams,0.0,Collision damage.
5516,5517,2022,22,Abu Dhabi Grand Prix,alpine,0.0,Water leak.

Agregamos un punto final "." a cada valor de *status* por que queremos agrupar estos resultados por constructores entonces esto nos facilitará el proceso. Ahora haremos uso de Siuba para obtener el DataFrame deseado.

In [31]:
from siuba import * 
from siuba.dply.vector import *

Agruparemos el dataframe por año, ronda, carrera y constructor posteriormente sumaremos los puntos de los constructores en cada una de ellas y el status de sus 2 conductores. 
Despues los pasos realizados son cambiar el formato de presentacion de status separandolos con un "split" pero como los mostrará como una lista y se ve mejor como cadena vectorizamos la función "join" para cada uno de los valores de status.

In [58]:
df=constructorResults2 >> group_by(_.year,_.round,_.raceId,_.constructorId)  >> summarize(points=_.points.sum(),status=_.status.sum())>>arrange (_.year,_.round)
df["status"]=df["status"].str.split(".",n=1)
df["status"]=[", ".join(x) for x in df["status"]]
df

,year,round,raceId,constructorId,points,status
0,2010,1,Bahrain Grand Prix,ferrari,43.0,"Finished, Finished."
1,2010,1,Bahrain Grand Prix,force_india,2.0,"Finished, Finished."
2,2010,1,Bahrain Grand Prix,hrt,0.0,"Overheating, Accident."
3,2010,1,Bahrain Grand Prix,lotus_racing,0.0,"+2 Laps, Hydraulics."
4,2010,1,Bahrain Grand Prix,mclaren,21.0,"Finished, Finished."
...,...,...,...,...,...,...
2754,2022,22,Abu Dhabi Grand Prix,haas,0.0,"+1 Lap, +1 Lap."
2755,2022,22,Abu Dhabi Grand Prix,mclaren,11.0,"Finished, Finished."
2756,2022,22,Abu Dhabi Grand Prix,mercedes,10.0,"Finished, Hydraulics."
2757,2022,22,Abu Dhabi Grand Prix,red_bull,40.0,"Finished, Finished."
2758,2022,22,Abu Dhabi Grand Prix,williams,0.0,"+1 Lap, Collision damage."

Ahora si, podemos observar los puntajes de cada constructor y los status de cada uno de sus corredores, por ronda, por año desde 2010 hasta 2022.

In [59]:
df.to_csv("constructorResults.csv", index=False)